import { Italianno,Nosifer } from "next/font/google";
import "./globals.css";

const italianno = Italianno({
  variable: "--font-italianno",
  subsets: ["latin"],
  weight:'400'
});

const nosifer = Nosifer({
  variable: "--font-nosifer",
  subsets: ["latin"],
  weight:'400'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${italianno.variable} ${nosifer.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
